name: actiontest

on:                # 이벤트 작성
  push:
    branches: ["master"] # master 브랜치에 push가 발생하면

jobs:
  build:
    runs-on: ubuntu-latest
    steps:               # 실제 수행할 작업 작성
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - name: Build
        run: go build -v ./...

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and release to DockerHub
        env:
          NAME: jiwon000
          REPO: actiontest
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest
